CREATE TABLE `MKT_DAILY_DATA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(45) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `MKT_DATE` date NOT NULL,
  `PRICE_OPEN` float DEFAULT NULL,
  `PRICE_HIGH` float DEFAULT NULL,
  `PRICE_CLOSE` float DEFAULT NULL,
  `PRICE_LOW` float DEFAULT NULL,
  `VOLUME` double DEFAULT NULL,
  `VOLUME_AMT` double DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=683890 DEFAULT CHARSET=utf8;
